version: "3"

services:
  web:
    expose:
      - "8000"
    ports:
      - "8000:8000"
    depends_on:
      - postgres

  postgres:
    image: postgres:14
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5433:5432"
    env_file:
      - ./.env

  migrate:
    depends_on:
      - postgres
    links:
      - postgres

  collectstatic:
    depends_on:
      - postgres
    links:
      - postgres

volumes:
  postgres_data: